llm:
  api_type: "openai" # or openai
  base_url: 'YOUR_BASE_URL'
  model: "gpt-3.5-turbo"
  api_key: "" # "loaded from environment variable"

embedding:
  api_type: "hf"  # or  ollama / openai.
  # base_url: "https://cfcus02.opapi.win/v1"  # or forward url / other llm url
  device: "cpu"
  api_key: "YOUR_API_KEY"
  model: "sentence-transformers/multi-qa-mpnet-base-cos-v1"
  cache_dir: ""
  dimensions: 768
  max_token_size: 8102
  embed_batch_size: 128
  embedding_func_max_async: 16
 
data_root:  "Data" # Root directory for data



working_dir: ./ # Result directory for the experiment
exp_name:  test1 # Experiment name
# 